version: '3'
services:
  data:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file: .data_env
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
#    or without Dockerfile after ./mvnw spring-boot:build-image
#    image: cloud-increment
    depends_on:
      - data
    env_file: .web_env
    ports:
      - '8080:8080'
volumes:
  pgdata: